apiVersion: v2
name: esports-analytics
description: Live eSports Analytics Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - esports
  - analytics
  - realtime
  - cs2

maintainers:
  - name: Platform Team
    email: platform@esports.dev

dependencies:
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: postgresql
    version: "13.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
